version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    ports:
      - "81:80"
    networks:
      multility_network:
        ipv4_address: 192.168.3.3

networks:
  multility_network:
    external: true